files:
  - source: 
    - /app/**/Bundle.properties
    - /core/**/Bundle.properties
    - /engines/**/Bundle.properties
    ignore:
      - /app/Test/**/Bundle.properties 
      - /app/application/**/Bundle.properties 
      - /app/branding/**/Bundle.properties
    translation: /**/Bundle_%locale_with_underscore%.properties
